version: "2"

run:
  # General run options
  timeout: "5m"
  tests: true
  issues-exit-code: 1
  allow-parallel-runners: false
  allow-serial-runners: false
  go: "1.24"
  relative-path-mode: wd

output:
  show-stats: true
  path-prefix: ""
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true

linters:
  # Start from the standard set and tweak from there
  default: standard

  enable:
    - govet
    - staticcheck
    - ineffassign
    - revive
    - gosec
    - unused
    - nolintlint

  disable:
    # Often too noisy for many projects, can be enabled later if desired
    - depguard
    - errcheck
    - gocyclo

  settings:
    revive:
      enable-default-rules: true
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: false
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: true
      generated-is-used: true
    nolintlint:
      allow-unused: true
      require-explanation: false
      require-specific: false

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  uniq-by-line: true
  whole-files: false

severity:
  # Schema requires this field even if you don't customize severities
  default: ""
